# ================================================================
# GLOBAL SETTINGS (Loads Regardless of TPM)
# ================================================================
set-option -sa terminal-override ",xterm*:Tc"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# tmux-sensible
set -s escape-time 20
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g default-terminal "screen-256color"
set -g status-keys emacs
set -g focus-events on
setw -g aggressive-resize on

# default split keys in the same directory
bind % split-window -h -c '#{pane_current_path}'
bind '"' split-window -v -c '#{pane_current_path}'

# = for horizontal split, - for vertical split
bind = split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

# Navigate panes with Alt + arrow keys (no prefix needed)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-H previous-window
bind -n M-L next-window

# ================================================================
# PLUGINS
# ================================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin "catppuccin/tmux"

if-shell "test -f ~/.tmux/plugins/tpm/tpm" \
  "run '~/.tmux/plugins/tpm/tpm'"
